# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test on webpack5

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cat package.json | jq '.devDependencies.webpack = "^5.0.0-beta.30"' > package.json.tmp && mv package.json.tmp package.json
    - run: cat package.json
    - run: yarn install --frozen-lockfile --check-files
    - run: yarn why webpack
    - run: yarn test
